### ISSUE TITLE
rsync problem

### ISSUE THREAD

**Issue by DenisMelnik** [skoobe/riofs#101]
Hello, I need help.
When I try to rsync files I get the following errors:
rsync: stat "/blahblahblah" failed: No such file or directory (2)
rsync: rename "blahblahblah" -> "blahblahblah2": No such file or directory (2)

I noticed that it is files more than 5 mb, I've modified config 

    <part_size type="uint">1000000000</part_size>
and do: killall -s USR1 riofs

but it didn't help

at the same time if i modify part size,for exmaple, to 1 - and do: killall -s USR1 riofs - any files won't rsync (the error above)

so i think problem is really in the part size in configs

Moreover,in order to ensure, i've modified part size to 150kb and really - files smaller than 150kb was transmitted, but files more than 150kb was transmitted with this error (yes, those files have normal size in place where they have been rsynced, but with some set of letters after ‘.jpg’ (e.g. blahblahblah.jpg.fEsHMj), so these files (pictures) doesn’t open in web interface, but if their just rename (remove these letters) then pictures is opened without problem).

**Comment by wizzard** [comment]
RioFS is not a fully POSIX compatible filesystem (e.g.: appending data to a file is not supported). Do not expect rsync to work properly with RioFS.
