### ISSUE TITLE
Random dismount on S3

### ISSUE THREAD

**Issue by drsku** [skoobe/riofs#102]
We have been using Riofs to mount and S3 bucket on EC2. Today, the first time we actually went live to the public, the bucket dismounted from the EC2 instance without warning, destroying our site.

Our developer says this is a common issue. Is this true? Is there a way of making it more reliable. We just built our entire strategy on this, so it's a little concerning...

Thanks

**Comment by wizzard** [comment]
Hello, I'm not aware of such issue. 
In order to start investigating your issue I'd like to have RioFS debug log file with reproduced issue (you can create it by running RioFS with -v command argument).

**Comment by drsku** [comment]
It turns out we aren't using Riofs. I thought we were. We are using S3fs. Our developers chose it because of the lack of support for Fstab from Riofs. Is that true?

**Comment by wizzard** [comment]
Yes, that's true, but that problem solves by 1 line of code in your startup script.

**Comment by drsku** [comment]
Thanks. Appreciate your help. Is riofs widely used for S3-> EC2 mounting vs S3FS?

**Comment by wizzard** [comment]
Sorry, I don't have this information.

**Comment by drsku** [comment]
OK. Thanks for your help. Much appreciated
