### ISSUE TITLE
Copy from S3 to EBS failing

### ISSUE THREAD

**Issue by drsku** [skoobe/riofs#104]
We host images on our platform in S3. These need to be copied in batch from S3 to EBS for processing by EC2.

We are finding that they are not copying reliably. And often they have zero size when copied. 

We have tried putting logging on, but this doesn't log anything at all.

Any thoughts?

Thanks

**Comment by wizzard** [comment]
Hello,

first of all, could you please show which command line arguments do you use with RioFS? (but please hide the real bucket name).

Then, in order to help you, I'll need to have "verbose" debug log file to find the reason of your issue.

**Comment by drsku** [comment]
We got another developer on it, who seems to have fixed it.
