### ISSUE TITLE
Invalid Accept-Encoding value

### ISSUE THREAD

**Issue by yurykats** [skoobe/riofs#118]
Accept-Encoding header is set to “identify” in http_connection.c

This is a typo! It should be “identity”. (see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

**Comment by yurykats** [comment]
This prevents riofs from being used against a custom S3 storage provider, since the said provider implements stricter header checks, and rejects riofs's request with 400:

14:34:38 [con] (http_connection_on_responce_cb http_connection.c:583) [con: 0x1b363a0] Server returned HTTP error: 400 (Bad Request). AWS message: Unsupported Accept-Encoding specified

**Comment by wizzard** [comment]
Great finding,
thank you!
