### ISSUE TITLE
empty directories not syncing with s3

### ISSUE THREAD

**Issue by sureshamk** [skoobe/riofs#119]
I created some empty directories , those are all not syncing with s3. If add some files , then it got added in bucket. But it should sync all the empty directories with bucket .

**Comment by wizzard** [comment]
Correct, you can't store an empty directory in S3, as it has no no concept of directories. 
If you really need to have an empty "directory", then create a hidden file in such directory (such as _.tmp_) and it will be synced to S3.

**Comment by sureshamk** [comment]
I have some situations to keep empty directories . In that situation how i can achieve it ?  I don't want to add any empty file to the created directory by a program

**Comment by wizzard** [comment]
Unfortunately this is a AWS S3 limitation, currently we can't do anything about this. Only a hidden file in such directory could help.
