### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by bcnx** [skoobe/riofs#120]
Hi,

running the latest RioFS on CentOS 7. 
We can successfully mount a bucket, but as soon as we do a rsync to the mount from a different server, we get the "Transport endpoint is not connected" error message and the mount is unresponsive. We need to unmount and mount again for the mount to be active again, but as soon as we launch a new rsync, the same issue occurs. 

At the same time we cannot delete files with for instance the "&" symbol in it's name. Maybe this is related, in such a way that the mount crashes on these funny filenames?

Thanks for looking into this!

BC

**Comment by bcnx** [comment]
This is in the dmesg output:

[ 1970.548668] riofs[3659]: segfault at 1f ip 00007f70de28a961 sp 00007fff20fb46c8 error 4 in libc-2.17.so[7f70de128000+1b6000]
[ 2429.528454] nf_conntrack: automatic helper assignment is deprecated and it will be removed soon. Use the iptables CT target to attach helpers instead.
[ 3459.397973] riofs[4365]: segfault at 1d ip 00007f5ff1e72961 sp 00007fff74743d38 error 4 in libc-2.17.so[7f5ff1d10000+1b6000]
[12589.451391] riofs[4973]: segfault at 1d ip 00007f78b274e961 sp 00007ffec1a73ec8 error 4 in libc-2.17.so[7f78b25ec000+1b6000]
[14991.160957] riofs[5016]: segfault at 30 ip 00007f594d72a985 sp 00007fff0dd25888 error 4 in libc-2.17.so[7f594d5c8000+1b6000]


RioFS seems to have crashed.

**Comment by wizzard** [comment]
Hello,

could you please help me to debug RioFS crash:

1) could you please run RioFS with ```gdb``` to get crash backtrace:
```gdb -ex "bt full" --batch -c core --args riofs [your arguments here] > /tmp/riofs_bt.txt```

just make sure that after "--args" you provide your usual command line arguments as if you run ```riofs```.  After you start RioFS try to reproduce the crash. If RioFS crashes please send me ```/tmp/riofs_bt.txt``` file (but please be aware that it could contain some sensitive data, such as file names. So it would be great if you run RioFS for some test bucket).

2) could you please provide me with detailed information how you managed to crash RioFS, which actions were performed just before it crashed? any additional information would be really helpful! Thank you!

**Comment by bcnx** [comment]
Hi,

 
As we were rather in a hurry to get things sorted, we decided to go with S3QL. This seems to be a better choice for our purposes, as it is fully compliant with POSIX. 

 
 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----

**Comment by wizzard** [comment]
Feel free to contact me directly if you need any further support.
