### ISSUE TITLE
Releasing a new Version

### ISSUE THREAD

**Issue by hierony94** [skoobe/riofs#121]
Dear @wizzard ,

How about releasing a new version.
I see the latest version is 0.6, and it released on Nov 26, 2013.

It's safe to use this version?
This release is 51 commit behind master.

Thank You

**Comment by wizzard** [comment]
Hello,

this is a really good idea!

Initially I planned to add a few new features and release the next version, but unfortunately I never had enough time/resources to finish my code.

I'll review the latest changes and release the new version in the next week.

Thank you for the idea!
