### ISSUE TITLE
RIOFS-Folder sync issue

### ISSUE THREAD

**Issue by raghav-malluviah** [skoobe/riofs#133]
Hi All,
 If i create folder on the S3 bucket using AWS console i am able to see those folder on my EC2 instance. But if i create any folder or directory in EC2 instance i am not able to see this folder in S3 bucket. 
If i just create file (using touch command) its working fine with out any issue. i.e. when i create simple file by using touch command i am able to see this file on S3 bucket.
 Same thing is not working for folders. Let me know what is the solution for this.

**Comment by wizzard** [comment]
Hello,

RioFS does not support empty folders (this is S3 limitation).

As a recommendation: add a "hidden" file (which starts with . ) into newly created directory, and then such directory will by uploaded to S3.
