### ISSUE TITLE
How does caching work? Under what conditions can it fail?

### ISSUE THREAD

**Issue by hughperkins** [skoobe/riofs#145]
Hi,

riofs is nice :-) . I tried s3fs first, but it was unworkably slow. riofs is nice and fast :-)

I think that it gets its speed partially/ a lot through aggressive caching.  In order to be able to use riofs without losign data, I just want to understand:
- what assumptions does the riofs caching make?
- under what conditions/actions can the caching fail/be out of date?

**Comment by wizzard** [comment]
There are several caching related parameters in `riofs.conf.xml`:
* dir_cache_max_time - time between sending requests to S3 server to get directory content. You can increase this timeout if you know that the remote directory content isn't changed by some other user.
* file_cache_max_time - if you locally remote a file, then we need to check if a file with the same name re-appeared remotely. Feel free to increase this timeout if you are the only S3 user.
* cache_dir_max_size - increase the size of cache dir to keep changes locally, that should potentially save time if you frequently access the same objects.

**Comment by hughperkins** [comment]
Thanks!
