### ISSUE TITLE
Does riofs support cn-north-1 region?

### ISSUE THREAD

**Issue by PinkGabriel** [skoobe/riofs#148]
Hi there~
I want to use riofs to mount a filesystem form aws s3. I'm sure my key pair is right because I've used it in s3fs(while it's too slow...). But when I mount riofs, I got this:

> 11:57:57 [con] (http_connection_on_response_cb http_connection.c:464) [con: 0x8be580] Got HTTP response from server! (76msec)
11:57:57 [con] (http_connection_on_response_cb http_connection.c:591) [con: 0x8be580] Server returned HTTP error: 400 (Bad Request). AWS message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
11:57:57 [con]  (http_connection_on_response_cb http_connection.c:602) [con: 0x8be580] Server returned HTTP error: 400 (Bad Request)! Retry ID: 19 of 20
11:57:57 [con] (http_connection_make_request http_connection.c:814) [con: 0x8be580] GET /testbucket/?acl  bucket: testbucket, host: s3.cn-north-1.amazonaws.com.cn, out_len: 0
11:57:57 [con] (http_connection_on_close http_connection.c:196) [con: 0x8be580] Connection closed !
11:57:57 [con] (http_connection_on_response_cb http_connection.c:464) [con: 0x8be580] Got HTTP response from server! (64msec)
11:57:57 [con] (http_connection_on_response_cb http_connection.c:591) [con: 0x8be580] Server returned HTTP error: 400 (Bad Request). AWS message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
11:57:57 [con]  (http_connection_on_response_cb http_connection.c:602) [con: 0x8be580] Server returned HTTP error: 400 (Bad Request)! Retry ID: 20 of 20
11:57:57 [con]  (http_connection_on_response_cb http_connection.c:605) [con: 0x8be580] Reached the maximum number of retries !
11:57:57 [con] (http_connection_release http_connection.c:183) [con: 0x8be580] Connection object is released!
11:57:57 [bclient]  (bucket_client_on_cb bucket_client.c:69) Failed to execute HTTP request !
11:57:57 [main]  (application_on_bucket_acl_cb main.c:494) Failed to get bucket ACL! Most likely you provided wrong AWS keys or bucket name !
11:57:57 [main] (application_destroy main.c:508) Destroying application !

I don't know if the config file format or url is right. help me please~
Thank you!

**Comment by wizzard** [comment]
Hello,
cn-north-1 region requires only protocol version 4, which is not currently supported by RioFS.
