### ISSUE TITLE
possibility to use HTTPS endpoint on different port

### ISSUE THREAD

**Issue by yelha** [skoobe/riofs#151]
Hello!
I have a question regarding HTTPS endpoints. We have an S3 compliant provider (not Amazon) which we want to mount a bucket from. But he provides an HTTPS endpoint on a different port than 443. Is there a possibility to state a port in the s3 section of the configuration file? I was not able to figure out, sorry.

Thank you!

**Comment by wizzard** [comment]
Hello,
you should be able to add `:port` to the end of endpoint URL in riofs.conf.xml configuration file.
But I'm not sure if RioFS will work with non AWS S3 provider (as I made a number of S3 related assumptions in the code).

**Comment by yelha** [comment]
Hi!
Thanks for your answer, we tested that but it did not recognize or ignore the stated port and made default https.
