### ISSUE TITLE
[Request] Digital Ocean S3 Spaces

### ISSUE THREAD

**Issue by RundleSG** [skoobe/riofs#152]
Is there any plans to add support for Digital Ocean's new S3 Object Storage, called "spaces"?

**Comment by wizzard** [comment]
Hello,
nope, I'm not planning to extend the current code.

**Comment by pjebs** [comment]
Digital Ocean spaces claims to be S3 compatible in terms of their API and how it can be interfaced by external clients. Should  riofs work in theory? (I haven't tried it)

**Comment by pjebs** [comment]
See: https://forum.seafile.com/t/digital-ocean-spaces-as-a-backend/4257/5

**Comment by wizzard** [comment]
I don't think RioFS can be used with Digital Ocean spaces without modifying the code, as I made a number of assumptions and hardcoded Amazon S3-specific strings.

**Comment by TheGP** [comment]
sad
