### ISSUE TITLE
Unable to rename files

### ISSUE THREAD

**Issue by random245** [skoobe/riofs#157]
Hi, 
I have an FS mounted with riofs, like so:
`/usr/local/bin/riofs -c /usr/local/etc/riofs/riofs.conf.xml -l /var/log/riofs.log -o allow_other --uid 8879 --gid 8878 mys3bucket /mymount/data`
When I cd into a mounted directory, the files all show up owned by the specified user/group. However, I cannot rename: I just get an "Operation not permitted". And in the logs:
```
^[[1;31mERROR!^[[0m [con: 0xf2d5d0] Server returned HTTP error: 403 (Forbidden)! Retry ID: 1 of 20
...
^[[1;31mERROR!^[[0m [con: 0xf2d5d0] Server returned HTTP error: 403 (Forbidden)! Retry ID: 20 of 20
^[[1;31mERROR!^[[0m [con: 0xf2d5d0] Reached the maximum number of retries !
^[[1;31mERROR!^[[0m Failed to rename !
```
It feels like I'm missing something obvious here. I have tried running riofs as root and as the user specified by the uid above. Ditto for running the move command.
Details:
```
# cat /etc/issue
Amazon Linux AMI release 2017.09
Kernel \r on an \m

# riofs --version
RioFS File System v0.8.0
Copyright (C) 2012-2014 Paul Ionkin <paul.ionkin@gmail.com>
Copyright (C) 2012-2014 Skoobe GmbH. All rights reserved.
Libraries:
 GLib: 2.36.3   libevent: 2.0.21-stable  fuse: 2.9  glibc: 2.17
Features:
 libevent backend method: epoll 
```
TIA!

**Comment by quancore** [comment]
riofs does not support file renaming.

**Comment by random245** [comment]
To answer my own question, it was a simple fix in the end - my bucket policy prevented writing :(

Now I can rename files (@quancore, thanks for your response, but I think it is only folder renaming that isn't supported).
