### ISSUE TITLE
Renaming folder

### ISSUE THREAD

**Issue by tombou** [skoobe/riofs#30]
Hi, I've found another issue. It's not possible to rename a folder using the mv command in ubuntu. It's a normal behaviour? Otherwise, it's possible to copy a folder and delete the old one after but it's not the best solution. Thank you!

**Comment by wavetossed** [comment]
This could be done by having a riofs mount option that specifies a max time or max number of child objects, and then the whole issue of long delays becomes irrelevant. The default settings would be for a very short time, and a small number of child objects, but people who understand the risk/issue, could mount riofs with a higher value which works for their use case.
