### ISSUE TITLE
Environment variables error 

### ISSUE THREAD

**Issue by cyikeda** [skoobe/riofs#37]
Hi,

I was able to get riofs working right after I installed, but after a ec2 reboot I'm no longer able to get the riofs command to work without encountering the following error:
07:43:34 [main](main main.c:831) Environment variables are not set!

I used the command export AWS_ACCESS_KEY_ID="" and export AWS_SECRET_ACCESS_KEY="", and was even able to echo out the values of both. But when I ran riofs --uid 1001 s3bucketname /mnt/s3, I got the error listed above.

Then I tried adding those keys to config file and tried running the command like this:
riofs -c ~/.config/riofs/riofs.conf.xml --uid 1001 s3bucketname /mnt/s3

But still got the same error listed above. I'm pretty confused and stuck now, any ideas?

The account I'm running the commands from has access to sudo and here are the permissions on the config file:
-rwxrwxrwx 1 root root 4384 Dec  7 07:03 ~/.config/riofs/riofs.conf.xml

**Comment by arabiaweather** [comment]
Got this resolved by making sure that i have uncommented the lines which contains the S3 credentials from the file "riofs.conf.xml"
