### ISSUE TITLE
Support for IAM Roles for EC2

### ISSUE THREAD

**Issue by Fuitad** [skoobe/riofs#58]
Heya,

I'd like to know if it's planned to support IAM Roles for Amazon EC2 (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) somewhere in the road map.

Thanks!

**Comment by timc13** [comment]
shouldn't this issue be kept open?

**Comment by dhilditch** [comment]
Would be good if this could be added.

**Comment by crunchytom** [comment]
s3fs supports -o iam_role="auto" which takes care of this automatically.  can't use riofs until it has a similar mechanism.  please reopen this issue.
