### ISSUE TITLE
Error running riofs inside of an upstart script

### ISSUE THREAD

**Issue by djensen47** [skoobe/riofs#96]
The upstart script I have is very simple:

```
#!upstart

description "RioFS"
author "djensen"

start on startup
stop on shutdown

env AWS_ACCESS_KEY_ID="<key>"
env AWS_SECRET_ACCESS_KEY="<secret>"

post-stop script
  killall riofs
end script

script
  exec /usr/local/bin/riofs -l /var/log/riofs.log --uid 33 --gid 33  --fmode 0755 --dmode 0755 foo /mnt/s3/foo
end script
```

In the logs, I see
```
ERROR! Got SIGTERM
```

If I run `/usr/local/bin/riofs -l /var/log/riofs.log --uid 33 --gid 33  --fmode 0755 --dmode 0755 foo /mnt/s3/foo` it works just fine.

**Comment by wizzard** [comment]
It's hard to tell why does it crash. Try to locate ```core``` file, that would help to investigate the crash reason.

Could you please double check that all RioFS dependencies (libevent, libxml, etc) are installed in the system path? 
Also, please try to execute RioFS as a different user (to check that there are no permissions issue).

**Comment by djensen47** [comment]
I'm still not sure what the issue was and wasn't sure where to find the core file. But I did resolve the problem. First and foremost, upstart gets "confused" if your script isn't perfect, meaning it didn't execute as expected. The only easy way to clear the "confusion" is to restart the machine. The core dump *may* have been happening while upstart was "confused."

Next, it seems like this option is required when using upstart: `--fuse-options="allow_other"`.

Finally, the upstart script **requires** the use of the `-f` flag. When `riofs` daemonizes, upstart cannot find the pid and then things start to go awry. I tried the `expect fork` and the `expect daemon` commands in the upstart script but neither seemed to work. So I simply let upstart handle the forking/daemonization aspect and just use the `-f` flag.

**Comment by djensen47** [comment]
Here's my new working script:

I also put the key and secret in the config file. So listing them below is a little redundant.

```
#!upstart

description "RioFS"
author "djensen"

start on (filesystem and static-network-up)
stop on shutdown

env AWS_ACCESS_KEY_ID="<key>"
env AWS_SECRET_ACCESS_KEY="<secret>"

script
  exec /usr/local/bin/riofs -f -l /var/log/riofs.log --uid 33 --gid 33 --fuse-options="allow_other" --fmode 0755 --dmode 0755 bucket /mnt/s3/bucket
end script
```

**Comment by wizzard** [comment]
Great to hear that you solved the issue! 

I'm quite sure that this information will be useful for other RioFS users.
Thank you!

**Comment by djensen47** [comment]
No problem, I also encapsulated the information in a quick blog post: http://build47.com/upstart-script-for-riofs-to-mount-an-aws-s3-bucket/
