### ISSUE TITLE
Can't Connect to ECS with S3. Server returned HTTP error: 500

### ISSUE THREAD

**Issue by alebeta90** [skoobe/riofs#97]
Hello friends!

I'm trying to use RioFS to connect to my storage system ECS because i read about RioFS and look like a good solution for manage my buckets.

this is the output: (if you need more verbouse i can send you the output with more details.)

ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 1 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 2 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 3 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 4 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 5 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 6 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 7 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 8 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 9 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 10 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 11 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 12 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 13 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 14 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 15 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 16 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 17 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 18 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 19 of 20
ERROR! [con: 0x25b5e20] Server returned HTTP error: 500 (Server Error)! Retry ID: 20 of 20
ERROR! [con: 0x25b5e20] Reached the maximum number of retries !
ERROR! Failed to execute HTTP request !
ERROR! Failed to get bucket ACL! Most likely you provided wrong AWS keys or bucket name !

Thanks a lot.!

**Comment by wizzard** [comment]
Hello, 
I've never seen 500 ERROR, such error indicates that there was a server error.

I need more details to help you with this error, could you please 
1) double check your bucket name, access key, secret key 
2) run RioFS in verbose mode (```-v```) and send me a few lines above and below error message

**Comment by alebeta90** [comment]
Hello @wizzard i'm just trying change to other bucket and works! was a problem in the bucket system. Thanks for the support. how i can mount the bucket in fstab?

**Comment by wizzard** [comment]
Great to hear that !
Currently RioFS does not support mounting in ```fstab```. 
I would recommend you to add a riofs command to /etc/rc.local startup file (or any other script, which your system executes at the startup).

**Comment by alebeta90** [comment]
Thanks! this works perfect! and other question, RioFS was testing using backup tools. Because im trying to backup some virtuals machines with veeam bakcup tool, but i have the error:

No such file or directory POSIX: Failed to write data to the file [PAth file.vbk]

**Comment by alebeta90** [comment]
@wizzard i was reading the documentation in the main page, and i see the following:

Known limitations

    Appending data to an existing file is not supported.

Maybe i can rewrite the existing file adding new data to the backup file and for this reason i have problem write data to the file. We have a solution for that? because is very important if we can do this kind of taks!

Thanks for your time! all the best

**Comment by wizzard** [comment]
Correct, RioFS does not support appending data to a file.

Unfortunately I'm not familiar with "veeam backup tool", and can't recommend you anything without information how files are created.

**Comment by alebeta90** [comment]
Perfect! i understand! thanks a lot for your time and for this good tool! all the best
