### ISSUE TITLE
Question on pool config and the max numbers of reads and writes

### ISSUE THREAD

**Issue by davegildea** [skoobe/riofs#98]
Hi Guys. 

Great job on RioFs we love it ! I have a question on the preferred config for a multithreaded application with up to 32 threads accessing the same Riofs mounted drive at the same time. There are 32 chips and 64GB ram on the server. What would be the best config as we are starting to see some issues where some files are only partially written to the s3.

Can we safely increase the numbers of concurrent operations from
```xml
<pool>
    <!-- number of concurrent connections for each type of operation -->
    <writers type="int">2</writers>
    <readers type="int">2</readers>

    <!-- number of concurrent connections for "other" operations,
         such as directory listing, object deleting, etc -->
    <operations type="int">4</operations>

    <!-- max requests in pool queue -->
    <max_requests_per_pool type="uint">100</max_requests_per_pool>
</pool>
```
to something like 
```xml
<pool>
    <!-- number of concurrent connections for each type of operation -->
    <writers type="int">32</writers>
    <readers type="int">32</readers>

    <!-- number of concurrent connections for "other" operations,
         such as directory listing, object deleting, etc -->
    <operations type="int">16</operations>

    <!-- max requests in pool queue -->
    <max_requests_per_pool type="uint">300</max_requests_per_pool>
</pool>
```

Do you have a sample/best practice config for a high powered server ?

Thanks

Dave

**Comment by wizzard** [comment]
RioFS is a single threaded application.

We use I/O event notification Kernel API (http://en.wikipedia.org/wiki/Epoll) which doesn't block the application execution.

The numbers which you specify in the pools' configuration mostly affect the Internet bandwidth.

The best is to try several options and measure the results.
